# Project: Dome
# Makefile created by Dev-C++ 5.5.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Dome.o
LINKOBJ  = Dome.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc D:/360data/Dev-Cpp/MinGW32/lib/libgdi32.a D:/360data/Dev-Cpp/MinGW32/lib/libgdiplus.a libSeaUI.a  -pg
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.7.2/include/c++"
BIN      = Dome.exe
CXXFLAGS = $(CXXINCS) -ansi -pg
CFLAGS   = $(INCS) -ansi -pg
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Dome.o: Dome.cpp
	$(CPP) -c Dome.cpp -o Dome.o $(CXXFLAGS)
